### PR TITLE
Timer

### PR DESCRIPTION
**Pull request by jhaemin**
### Feature

- Create `Timer` component

### Refactor

- Change the way generate component selector of the outermost element

### CODE REVIEW

**Comment by choibumsu** [comment]
I confirmed your Pull Request.

Very Good.

**Comment by JeongBin0227** [comment]
I confirmed your Pull Request.

Very good code!
But I need a brief explanation of your code.

**Comment by jhaemin** [comment]
> I confirmed your Pull Request.
> 
> Very good code!
> But I need a brief explanation of your code.

@JeongBin0227 
Sure why not.
Tomorrow, let's talk about this week's sprint in more detail while pair programming.

**Comment by JeongBin0227** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by JeongBin0227** [comment]
Reconfirm

**Pull request merged**
